#!/bin/sh -e

INSTALL=$(readlink -e "$0")
DOTFILES=$(dirname "$INSTALL")
BACKUP=$HOME/.dotfiles_backup/$(date -Iseconds)

mkdir -p $BACKUP

cd $DOTFILES
for FILE in *; do
	[ "$FILE" = "install" ] && continue

	SYMLINK=$HOME/.$FILE
	TARGET=$DOTFILES/$FILE
	[ "$(readlink -e $SYMLINK)" = "$TARGET" ] && continue

	if [ -e $SYMLINK ]; then
		echo "Backing up $SYMLINK to $BACKUP..."
		mv $SYMLINK $BACKUP
	fi

	echo "Installing $SYMLINK..."
	ln -sf $TARGET $SYMLINK
done

# vim specific install
mkdir -p $HOME/.vim/bundle
git clone https://github.com/Shougo/neobundle.vim $HOME/.vim/bundle/neobundle.vim
mkdir -p $HOME/.vim/swap
mkdir -p $HOME/.vim/undo
